/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as BriefingsIndexRouteImport } from './routes/briefings/index'
import { Route as BriefingsSlugRouteImport } from './routes/briefings/$slug'
import { Route as PlacesIndexRouteImport } from './routes/places/index'
import { Route as PlacesSlugRouteImport } from './routes/places/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsIndexRoute = BriefingsIndexRouteImport.update({
  id: '/briefings/',
  path: '/briefings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsSlugRoute = BriefingsSlugRouteImport.update({
  id: '/briefings/$slug',
  path: '/briefings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/briefings/$slug': typeof BriefingsSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/briefings/': typeof BriefingsIndexRoute
  '/places/': typeof PlacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/briefings/$slug': typeof BriefingsSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/briefings': typeof BriefingsIndexRoute
  '/places': typeof PlacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/briefings/$slug': typeof BriefingsSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/briefings/': typeof BriefingsIndexRoute
  '/places/': typeof PlacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/briefings/$slug'
    | '/places/$slug'
    | '/briefings/'
    | '/places/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/briefings/$slug'
    | '/places/$slug'
    | '/briefings'
    | '/places'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/briefings/$slug'
    | '/places/$slug'
    | '/briefings/'
    | '/places/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  BriefingsSlugRoute: typeof BriefingsSlugRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
  BriefingsIndexRoute: typeof BriefingsIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings/': {
      id: '/briefings/'
      path: '/briefings'
      fullPath: '/briefings/'
      preLoaderRoute: typeof BriefingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings/$slug': {
      id: '/briefings/$slug'
      path: '/briefings/$slug'
      fullPath: '/briefings/$slug'
      preLoaderRoute: typeof BriefingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  BriefingsSlugRoute: BriefingsSlugRoute,
  PlacesSlugRoute: PlacesSlugRoute,
  BriefingsIndexRoute: BriefingsIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
